---
#Install RPM Fusion repos
#
#This might move off to a separate role
#- name:  Install RPM Fusion Free
#  yum: name={{ item }}
#       state=present
#         
#  with_items:
#    - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_current }}.noarch.rpm
#    - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_current }}.noarch.rpm


#update all packages
- name: upgrade all pacakges
  dnf: name=* state=latest

# Commenting out for testing
    #notify:
    #  - Reboot computer
    #  - Wait for reboot

