---    
# Install packages from pip
  - name: i3pystatus
    pip: name=i3pystatus executable=pip3
   
  - name: beautifulsoup4
    pip: name=beautifulsoup4 executable=pip3
    
  - name: colour
    pip: name=colour executable=pip3
 
  - name: net-ifaces
    pip: name=netifaces executable=pip3
    
  - name: cherrypy
    pip: name=CherryPy executable=pip3
    
  #- name: rdiff-backup
  #  pip: name=rdiff-backup executable=pip3    
    
  
