---
- hosts: testing
  gather_facts: no
  become: true
  become_method: sudo
  remote_user: curtis
  #become: yes
  #become_user: root
  #become_user: curtis

  vars_files:
    - variables/fedora_vars.yml



# adding line
# can dry run with ansible-playbook playbook.yml --check --become-method=su -K
#
# or with the sudo method, to check the playbook:
# ansible-playbook playbook.yml -vvv --check
#
# change this to:
# ansible-playbook playbook.yml -vvv -K
# This will ask for the sudo password
#
  roles:
      - test_vars
      - initial
      #- rpmfusion
      #- common
      #- pip
      #- configs
      #- fonts
      #- vim_curl
      #- ipv6


