---
#reboot the workstation
- name: Reboot computer
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true
    

- name: Wait for reboot
  become: no
  local_action: 
      wait_for host={{ ansible_ssh_host }}
      state=started
      port=22 
      timeout=450
      delay=120
      connect_timeout=300
